package com.webapplogin.webapplogin.Entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name ="Users")
public class User {


    @Id //--> IMPORTANTE.
    @Column
    @GeneratedValue(strategy = GenerationType.IDENTITY) //--> nota: siccome abbiamo messo autogenerated nel data.sql non mettiamo l'id 1. perchè non è necessario 2. perchè potrebbe creare problemi successivamente quando facciamo richieste post di generazione nuovi utenti.
   public Integer id;
    @Column
   public String name;
    @Column
   public String surname;
    @Column
   public String username;
    @Column
   public String password;
    @Column
   public String email;
    @Column
    public String role;
}