spring.application.name=WebAppLogin
spring.datasource.url=jdbc:h2:mem:database
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=User
spring.datasource.password=Password


spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=create

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/db

server.port=9090


spring.sql.init.mode=always

spring.jpa.show-sql=true

logging.level.org.springframework.security=DEBUG